### ISSUE TITLE
UnicodeEncodeError The input .md file in simplified Chinese

### ISSUE THREAD

**Issue by Lydiagugugaga** [MartinPacker/md2pptx#163]
`UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 23: surrogates not allowed`

I'm trying to convert a md file whose content is in Simplified Chinese, but I'm encountering encoding problems. I've read that the latest version mentions fixing #161, but I still can't get it to work on my end, so I'd like to ask what's the best way to fix it.

**Comment by MartinPacker** [comment]
Thank you for reporting this.

I'm away from my computer for the next couple of days- so can't look at this right away.

Can you somehow get me a minimal reducible example? I will also say that a workaround might be using a hexadecimal entity reference. But that's probably not a scalable behaviour.

**Comment by Lydiagugugaga** [comment]
> Thank you for reporting this.
> 
> I'm away from my computer for the next couple of days- so can't look at this right away.
> 
> Can you somehow get me a minimal reducible example? I will also say that a workaround might be using a hexadecimal entity reference. But that's probably not a scalable behaviour.

I just try to input  `python md2pptx output.pptx < 222.md`
![image](https://github.com/user-attachments/assets/fd3d3dfa-f3e1-483f-b943-f643b2218f8d)

**Comment by MartinPacker** [comment]
Thanks. I need the 222.md file - or a minimal version of it. (No confidential etc data.)

**Comment by Lydiagugugaga** [comment]
Thanks for your reply. Here is just an example markdown file:

[222.md](https://github.com/user-attachments/files/16707980/222.md)

**Comment by MartinPacker** [comment]
Thanks for this. I note your attempt to use `<p>` paragraph tags. Those aren't supported by md2pptx - if I remember correctly. I would use asterisks `*` instead.

If you think paragraph tags should be supported - and have a clear idea as to how the should be rendered - please open another issue.

**Comment by Lydiagugugaga** [comment]
> Thanks for this. I note your attempt to use `<p>` paragraph tags. Those aren't supported by md2pptx - if I remember correctly. I would use asterisks `*` instead.
> 
> If you think paragraph tags should be supported - and have a clear idea as to how they should be rendered - please open another issue.

Thanks for your reply.
About <p>  paragraph tags, I thought it was the problem before, but I actually tried removing it and using the generic .md form and it doesn't work either.

**Comment by MartinPacker** [comment]
Right. BBEdit (one of my editors of choice) thinks the file is UTF-8 but I suspect it isn't. Sniffing what it is is an approach I might take.

**Comment by MartinPacker** [comment]
This is strange: My run with your file yields this:

```
md2pptx Markdown To Powerpoint Converter 5.0.2+ 15 August, 2024
===============================================================

Open source project: https://github.com/MartinPacker/md2pptx

External Dependencies:

  Python: 3.9.6
  python-pptx: 0.6.23
  Pillow: 10.3.0
  CairoSVG: Not Installed
  graphviz: Not Installed

Internal Dependencies:

  funnel: 0.1
  runPython: 0.4

No slide to document metadata on. Continuing without it.

Slides:
=======

   1   初学者骑车之路：掌握自行车技巧的必备指南
   2   自行车基础知识
   3       自行车的组成部分
   4       自行车的类型和用途
   5   准备骑行前的注意事项
   6       自行车装备和保养
   7       骑行安全知识和规则
   8   学习骑行技巧
   9       自行车平衡和姿势
  10       踩踏和换挡技巧
  11       转弯和刹车技巧
  ```

**Comment by MartinPacker** [comment]
I'm suspecting your problem is with python-pptx, rather than md2pptx. But I keep an open mind about this.

**Comment by Lydiagugugaga** [comment]
> I'm suspecting your problem is with python-pptx or lxml, rather than md2pptx. But I keep an open mind about this.

Thank you so much for helping me with this question.
I've referenced some of the previously mentioned issues and also tried the python-pptx version change which is currently v0.6.23. But is didn't work.

If it's a problem with python-pptx or lxml, what do you suggest to fix it?

**Comment by MartinPacker** [comment]
I've just fixed a problem with numeric character references. So **with the very latest push** a workaround for you might well be to use character references such as `&#dc80;`. Fiddly, I know.

**Comment by Lydiagugugaga** [comment]
> So **with the very latest push** a workaround for you might well be to use character references such as `&#dc80;`. Fiddly, I know.

Thank you very much.
I'll try it.

**Comment by MartinPacker** [comment]
Please let me know how you get on. And do you think the text is really UTF-16 rather than UTF-8? The U+DC80 character isn't valid in UTF-8, apparently.

(And I just pushed some doc changes after the one that fixes numeric character references - so don't get confused by what the latest commit says.)

**Comment by Zengfanxu1111** [comment]
I'm still having this encoding issue—neither UTF-8 nor UTF-16 works. Could you please test and help me resolve it?

**Comment by Zengfanxu1111** [comment]
[codetest.md](https://github.com/user-attachments/files/20408636/codetest.md)
[codetest.pptx](https://github.com/user-attachments/files/20408637/codetest.pptx)
here is the source file,when I run the program,I got this result:
Slides:
=======

   1   涓�鏂囨祴璇�
   2   涓�鏂囨祴璇�
   3       涓�鏂囨祴璇�
   4       Here Is  A Table

Processing complete.
Elapsed time: 0.04s

Thanks!

**Comment by MartinPacker** [comment]
Is that the only character that is misunderstood?

**Comment by Zengfanxu1111** [comment]
As long as it's in Chinese, it will be misunderstood

**Comment by Zengfanxu1111** [comment]
![Image](https://github.com/user-attachments/assets/5b9b2127-e291-416a-b839-b039b8f73855)
![Image](https://github.com/user-attachments/assets/4dbdd18f-a227-4955-b4e5-0a169954e2bc)
here is the differences between chinese and english

**Comment by Zengfanxu1111** [comment]
I solved it ,I found that if I use run_pyto.py to run it,it will not make mistake,but if I use terminal  ,    it will make error
